apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: agroconnect


resources:
- ../../base/ingress-network.yaml
- ../../base/karpenter-nodepool.yaml
- namespace.yaml
- ../../base/frontend
- ../../base/backend
- ../../base/postgres

images:
- name: BACKEND_IMAGE
  newName: 794038236323.dkr.ecr.us-east-2.amazonaws.com/agroconnect-prod/backend
  newTag: sha-ac30956
- name: FRONTEND_IMAGE
  newName: 794038236323.dkr.ecr.us-east-2.amazonaws.com/agroconnect-prod/frontend
  newTag: sha-ac30956

patches:
- path: patches/backend-replicas.yaml
- path: patches/frontend-replicas.yaml
- path: patches/resource-limits.yaml

commonLabels:
  environment: production
  managed-by: argocd

commonAnnotations:
  deployment.kubernetes.io/revision: "1"
