apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: agroconnect-staging

resources:
  - ../../base/frontend
  - ../../base/backend
  - namespace.yaml

images:
  - name: FRONTEND_IMAGE
    newName: 794038236323.dkr.ecr.us-east-2.amazonaws.com/agroconnect-prod/frontend
    newTag: sha-558abc4
  - name: BACKEND_IMAGE
    newName: 794038236323.dkr.ecr.us-east-2.amazonaws.com/agroconnect-prod/backend
    newTag: sha-558abc4

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: frontend
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: backend

commonLabels:
  environment: staging
